name: Build Paper

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:TL2024-2024-09-22-full

    steps:
      - uses: actions/checkout@v4
      - run: latexmk -shell-escape -pdf main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: main.pdf
